### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by MindaugasJucius** [gkye/ComplimentaryGradientView#6]
It would be wonderful if there was carthage support

**Comment by gkye** [comment]
I'll add it later today :)

**Comment by gkye** [comment]
Could you please test these in your `Cartfile`?

`github "gkye/ComplimentaryGradientView" "cartageSupport"`
``github "gkye/ComplimentaryGradientView" "master"`
`github "gkye/ComplimentaryGradientView"` **(Doesnt work for some reason)**

for some strange reason I'm able to install from the `cartageSupport` and `master` branch when added to the `Cartfile` but cant when i leave out the branch. Is this supposed to happen? (I have 0 experience with Carthage  ):

**Comment by MindaugasJucius** [comment]
@gkye sorry I wasn't available, will test this and report back to you
